### PR TITLE
zh_CN.lang

### PR DESCRIPTION
**Pull request by DYColdWind**

### CODE REVIEW

**Comment by zabi94** [comment]
Thanks! Are some lines left out intentionally?

**Comment by DYColdWind** [comment]
lines？Such as.. If you're talking about translation. Yes, I did not translate. sorry

**Comment by zabi94** [comment]
Do you plan on finishing it or should I add it like it is?

**Comment by DYColdWind** [comment]
Ok, I'll see if I can finish this week. I've been a little busy lately

**Comment by zabi94** [comment]
Sure, no hurry, I'll keep the pull request open until you can finish

**Pull request merged**
